apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https-default
  namespace: {{.Release.Namespace}}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  redirectScheme:
    scheme: "https"
    permanent: true
