apiVersion: v2
description: OpenLdap test / example server
name: openldap-test
home: https://github.com/EugenMayer/docker-image-ldapexample
version: 0.2.2
appVersion: 0.1.0
keywords:
  - benchmark
  - network
  - tools
  - directory
  - test
sources:
  - https://github.com/EugenMayer/helm-charts/tree/main/charts/openldap-test
dependencies:
  - name: common
    # https://artifacthub.io/packages/helm/truecharts-library-charts/common
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ''
    alias: ''
    tags: []
    import-values: []
type: application
