name: postgres-pgdump-backup
description: Backup postgres databases using pg_dump, retention and schedules
version: 0.7.5
apiVersion: v2
appVersion: 16
keywords:
  - postgres
  - backup
  - retention
  - pg_dump
sources:
  - https://github.com/EugenMayer/helm-charts/tree/main/charts/postgres-pgdump-backup
  - https://github.com/prodrigestivill/docker-postgres-backup-local
home: https://github.com/EugenMayer/helm-charts/tree/main/charts/postgres-pgdump-backup
dependencies:
  - name: common
    # https://github.com/truecharts/public/blob/master/charts/library/common/Chart.yaml
    version: 28.16.6
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
