kubeVersion: ">=1.24.0-0"
apiVersion: v2
name: iobroker
version: 0.2.6
# see https://hub.docker.com/r/iobroker/iobroker/tags
appVersion: v9.1.2
description: home automation via ioBroker
home: https://github.com/EugenMayer/helm-charts/tree/main/charts/iobroker
deprecated: false
sources:
  - https://www.iobroker.net/
  - https://github.com/EugenMayer/helm-charts/tree/main/charts/iobroker
  - https://github.com/buanet/ioBroker.docker
keywords:
  - iobroker
  - home-automation
dependencies:
  - name: common
    # https://artifacthub.io/packages/helm/truecharts-library-charts/common
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
type: application
