name: whoami-tls
description: Whoami with a self-signed certificate - as simple as that
version: 0.1.3
apiVersion: v2
appVersion: 0.1.0
keywords:
  - network
  - tools
  - development
sources:
  - https://github.com/EugenMayer/helm-charts/tree/main/charts/whoami
home: https://github.com/EugenMayer/helm-charts/tree/main/charts/whoami
dependencies:
  - name: common
    # https://github.com/truecharts/public/blob/master/charts/library/common/Chart.yaml
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ''
    alias: ''
    tags: []
    import-values: []
type: application
