image:
  # https://github.com/EugenMayer/docker-image-whoami-tls
  repository: ghcr.io/eugenmayer/whoami-tls
  tag: 0.1.0
  pullPolicy: Always

securityContext:
  container:
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
    readOnlyRootFilesystem: true

service:
  main:
    ports:
      main:
        port: 443
        targetPort: 443
        protocol: https

workload:
  main:
    replicas: 1
    strategy: Recreate
    type: Deployment
    podSpec:
      containers:
        main:
          probes:
            readiness:
              port: 443
              type: https
              spec:
                initialDelaySeconds: 5
                periodSeconds: 5
                failureThreshold: 2
            liveness:
              enabled: true
              type: https
              port: 443
              spec:
                initialDelaySeconds: 5
                periodSeconds: 5
                failureThreshold: 2

ingress:
  main:
    enabled: false
    primary: true
    required: false
    ingressClassName: ''
    targetSelector:
      main: main
    hosts:
      - host: whoami.local
        paths:
          - path: /
            pathType: Prefix

portal:
  open:
    enabled: false
