name: cert-manager-external-account-bindings-cloudflare-config
description: Cert-Manager config for ACME via Cloudflare (DNS01) with external account bindings like for google trust services
version: 0.1.1
apiVersion: v2
appVersion: 1.0.0
