acme:
  name: gtc
  server: "https://dv.acme-v02.api.pki.goog/directory"
  dns:
    email:
    secret:
      name:
      key:
  externalAccountBinding:
    keyid:
    secret:
      name:
      key:
    keyAlgorithm: HS256
