name: whatsmyip
description: What's my ip - as simple as that
version: 1.3.2
apiVersion: v2
appVersion: 0.0.1
keywords:
  - network
  - tools
  - development
sources:
  - https://github.com/EugenMayer/helm-charts/tree/main/charts/whatsmyip
home: https://github.com/EugenMayer/helm-charts/tree/main/charts/whatsmyip
dependencies:
  - name: common
    # https://github.com/truecharts/public/blob/master/charts/library/common/Chart.yaml
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
type: application
