kubeVersion: ">=1.24.0-0"
apiVersion: v2
name: vulnz-nvd-mirror
version: 0.7.1
appVersion: 7.3.0
description: NVD api mirror and cache
home: https://github.com/EugenMayer/helm-charts/tree/main/charts/vulnz-nvd-mirror
deprecated: false
keywords:
  - network
  - tools
  - development
sources:
  - https://github.com/EugenMayer/helm-charts/tree/main/charts/vulnz-nvd-mirror
  - https://github.com/jeremylong/Open-Vulnerability-Project/tree/main/vulnz
dependencies:
  - name: common
    # https://github.com/truecharts/public/blob/master/charts/library/common/Chart.yaml
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
type: application
