kubeVersion: ">=1.24.0-0"
apiVersion: v2
name: gradle-build-cache
version: 0.1.2
appVersion: 21.2
description: Hosts the official gradle build cache node
home: https://github.com/EugenMayer/helm-charts/tree/main/charts/gradle-build-cache
deprecated: false
keywords:
  - network
  - tools
  - development
sources:
  - https://github.com/EugenMayer/helm-charts/tree/main/charts/gradle-build-cache
dependencies:
  - name: common
    # https://github.com/truecharts/public/blob/master/charts/library/common/Chart.yaml
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
type: application
